name: SonarCloud
on:
  workflow_dispatch:
  
jobs:
  sonarqube:
    name: SonarQube
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Flutter
        uses: subosito/flutter-action@v2 # Action to set up Flutter
        with:
          channel: 'stable'
      # The analysis requires to retrieve dependencies and build successfully
      - name: Build
        run: flutter pub get
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
